"""Dua bahasa / Two languages: Bahasa Melayu (ms) + English (en)."""
from __future__ import annotations

STRINGS = {
    "ms": {
        "app_title": "BE 2026 - Isi borang (semak pratonton sebelum eksport)",
        "tab_main": "Borang",
        "tab_settings": "Tetapan",
        "tab_terminal": "Terminal",
        "template_label": "Templat XLSX anda:",
        "pick_btn": "Pilih...",
        "pick_title": "Pilih templat BE2026 anda",
        "cui_label": "CUI:",
        "company_label": "Syarikat:",
        "year_label": "Tahun:",
        "ai_frame": "AI (pilihan - data tambahan syarikat)",
        "provider_label": "Penyedia:",
        "provider_auto": "Auto",
        "provider_openrouter": "OpenRouter",
        "provider_gemini": "Gemini langsung",
        "model_label": "Model:",
        "ai_search_btn": "3) Cari dengan AI",
        "ai_hint": "(tetapkan kunci dalam tab Tetapan)",
        "step1": "1) Muat templat",
        "step2": "2) Cari dalam talian",
        "agree_all": "Setuju semua",
        "uncheck_all": "Nyahpilih semua",
        "use_proposed": "Guna Cadangan -> AKHIR",
        "use_alternate": "Guna Alternatif -> AKHIR",
        "edit_final": "Edit AKHIR (baris dipilih)",
        "export_btn": "4) Eksport XLSX lengkap",
        "col_use": "✓", "col_field": "Medan borang", "col_cell": "Sel",
        "col_proposed": "Nilai dijumpai (cadangan)", "col_source": "Sumber",
        "col_conf": "Keyakinan", "col_alt": "Alternatif / Anggaran",
        "col_altsrc": "Sumber alt.", "col_final": "AKHIR (ditulis ke xlsx)",
        "ready_msg": ("Sedia. Langkah 1: muat templat anda, Langkah 2: cari dalam talian, "
                      "Langkah 3 (pilihan): cari dengan AI, semak jadual, Langkah 4: eksport."),
        # --- tab Tetapan ---
        "set_lang": "Bahasa / Language:",
        "set_or_key": "Kunci OpenRouter:",
        "set_gem_key": "Kunci Gemini:",
        "set_get_keys": "Dapatkan kunci: openrouter.ai/keys  |  aistudio.google.com/apikey",
        "set_show": "Tunjuk kunci",
        "set_provider": "Penyedia AI:",
        "set_model": "Model AI:",
        "set_find_best": "Cari model terbaik",
        "set_use_model": "Guna model dipilih",
        "set_save": "Simpan tetapan",
        "set_saved": "Tetapan disimpan.",
        "set_note": "Kunci disimpan setempat dalam config/settings.json (jangan kongsi fail ini).",
        "term_clear": "Padam terminal",
        "term_hint": "Memapar live: carian ANAF/BNR, prompt & respons AI, ranking model, eksport.",
        "set_best_hint": "Klik «Cari model terbaik» untuk senarai live OpenRouter (percuma dahulu, kemudian termurah).",
        "set_col_model": "Model", "set_col_price": "Harga/1J token",
        "set_col_ctx": "Konteks", "set_col_why": "Kenapa disyorkan",
        "why_free": "PERCUMA",
        "why_cheap": "Murah",
        "why_bigctx": "Konteks besar",
        # --- mesej/log ---
        "dlg_template": "Templat",
        "msg_no_fields": "Tiada medan dikesan (perlu susun atur A=Penunjuk B=Nilai atau token {{PLACEHOLDER}}).",
        "err_template": "Ralat templat",
        "warn_template_first": "Muat templat yang sah dahulu.",
        "msg_searching": "Mencari dalam talian CUI={cui} tahun={tahun} ...",
        "msg_preview_ready": ("Siap: {n} baris pratonton. SEMAK ruangan AKHIR sebelum eksport. "
                              "Dwicalon baris untuk edit nilai akhir. Anggaran ditanda ANGGARAN/AI."),
        "msg_online_first_note": "Nota: carian dalam talian dijalankan dahulu, kemudian AI menambah data.",
        "msg_ai_searching": "AI ({model}) mencari data tentang: {nama} ...",
        "msg_ai_touched": ("AI menyentuh {n} baris: nilai AI jadi cadangan utama jika kosong, "
                           "atau Alternatif untuk perbandingan. Sila semak sebelum eksport!"),
        "msg_final_proposed": "AKHIR = nilai cadangan (dalam talian/AI) untuk semua baris.",
        "msg_final_alt": "AKHIR = alternatif/anggaran kedua (di mana ada).",
        "dlg_edit": "Edit",
        "msg_pick_row": "Pilih satu baris dahulu.",
        "dlg_final": "Nilai akhir",
        "dlg_export": "Eksport",
        "msg_export_empty": "Tiada untuk dieksport - tekan 'Cari dalam talian' dahulu.",
        "msg_export_unchecked": "Semua baris dinyahpilih. Tandakan sekurang-kurangnya satu.",
        "msg_export_done": "Eksport berjaya: {out} ({n} medan ditulis). Format templat dikekalkan.",
        "msg_export_popup": "Siap:\n{out}\n\n{n} medan ditulis.",
        "err_search": "Ralat carian",
        "err_ai": "Ralat AI",
        "err_export": "Ralat eksport",
        "msg_models_live": "Model live dimuat ({n}). Pilih satu, kemudian «Guna model dipilih».",
        "msg_models_fallback": "Luar talian - senarai simpanan ditunjuk.",
        "msg_model_set": "Model ditetapkan: {m}",
        "msg_pick_model": "Pilih satu model dahulu.",
        "tpl_line": "Templat: {p} | helaian: {s} | medan dikesan: {n}",
        "msg_busy_template": "Memuat templat…",
        "msg_busy_search": "Mencari dalam talian (ANAF/BNR)…",
        "msg_busy_ai": "AI sedang mencari data…",
        "msg_busy_models": "Memuat senarai model…",
        "msg_busy_export": "Mengeksport XLSX…",
        "summary_btn": "Ringkasan",
        "sum_title": "Ringkasan borang",
        "sum_save": "Simpan txt",
        "sum_close": "Tutup",
        "sum_template": "Templat",
        "sum_company": "Syarikat/CUI",
        "sum_year": "Tahun",
        "sum_complete": "Lengkap",
        "sum_filled": "berisi",
        "sum_empty": "kosong",
        "sum_excluded": "dikecualikan (☐)",
        "sum_by_source": "Ikut sumber",
        "sum_by_sheet": "Ikut helaian",
        "sum_missing": "Medan kosong — perlu perhatian",
        "sum_detail": "Semua medan (detail lengkap)",
        "sum_none": "(tiada)",
        "sum_novalue": "(kosong)",
        "sum_saved": "Ringkasan disimpan: {out}",
        "sum_empty_rows": "Tiada baris — buat carian dahulu.",
        "estimate_btn": "3b) Auto-anggar baki",
        "msg_busy_estimate": "AI menganggar baki…",
        "msg_no_empty": "Tiada medan kosong — semua sudah berisi!",
        "sheet_label": "Helaian:",
        "sheet_all": "Semua",
        "dossier_btn": "Dosier TXT",
        "dos_title": "Dosier syarikat",
        "dos_need_name": "Isi nama syarikat (atau CUI) dahulu.",
        "dos_searching": "Menyemak {nama} merata sumber internet…",
        "dos_done": "Dosier siap: {status} ({n} bukti) → {out}",
        "dos_popup": "{nama}\nStatus: {status}\n\nDisimpan:\n{out}",
        "msg_busy_dossier": "Menyemak syarikat…",
        "msg_formula_skipped": " + {n} sel formula dilindungi",
        "stop_btn": "■ Berhenti",
        "msg_stopped": "Dihentikan oleh pengguna — hasil dibuang.",
        "empty_cui": "(kosong)",
        "unnamed": "(tidak dinyatakan)",
        "default_export_name": "BE2026_lengkap.xlsx",
    },
    "en": {
        "app_title": "BE 2026 - Fill form (review preview before export)",
        "tab_main": "Form",
        "tab_settings": "Settings",
        "tab_terminal": "Terminal",
        "template_label": "Your XLSX template:",
        "pick_btn": "Browse...",
        "pick_title": "Select your BE2026 template",
        "cui_label": "CUI:",
        "company_label": "Company:",
        "year_label": "Year:",
        "ai_frame": "AI (optional - extra company data)",
        "provider_label": "Provider:",
        "provider_auto": "Auto",
        "provider_openrouter": "OpenRouter",
        "provider_gemini": "Direct Gemini",
        "model_label": "Model:",
        "ai_search_btn": "3) Search with AI",
        "ai_hint": "(set keys in the Settings tab)",
        "step1": "1) Load template",
        "step2": "2) Search online",
        "agree_all": "Accept all",
        "uncheck_all": "Uncheck all",
        "use_proposed": "Use Suggested -> FINAL",
        "use_alternate": "Use Alternative -> FINAL",
        "edit_final": "Edit FINAL (selected row)",
        "export_btn": "4) Export complete XLSX",
        "col_use": "✓", "col_field": "Form field", "col_cell": "Cell",
        "col_proposed": "Found value (suggested)", "col_source": "Source",
        "col_conf": "Confidence", "col_alt": "Alternative / Estimate",
        "col_altsrc": "Alt. source", "col_final": "FINAL (written to xlsx)",
        "ready_msg": ("Ready. Step 1: load your template, Step 2: search online, "
                      "Step 3 (optional): search with AI, review the table, Step 4: export."),
        # --- Settings tab ---
        "set_lang": "Bahasa / Language:",
        "set_or_key": "OpenRouter key:",
        "set_gem_key": "Gemini key:",
        "set_get_keys": "Get keys: openrouter.ai/keys  |  aistudio.google.com/apikey",
        "set_show": "Show keys",
        "set_provider": "AI provider:",
        "set_model": "AI model:",
        "set_find_best": "Find best model",
        "set_use_model": "Use selected model",
        "set_save": "Save settings",
        "set_saved": "Settings saved.",
        "set_note": "Keys are stored locally in config/settings.json (do not share this file).",
        "term_clear": "Clear terminal",
        "term_hint": "Live view: ANAF/BNR lookups, AI prompts & responses, model ranking, export.",
        "set_best_hint": "Click “Find best model” for the live OpenRouter list (free first, then cheapest).",
        "set_col_model": "Model", "set_col_price": "Price/1M tokens",
        "set_col_ctx": "Context", "set_col_why": "Why recommended",
        "why_free": "FREE",
        "why_cheap": "Cheap",
        "why_bigctx": "Big context",
        # --- messages/log ---
        "dlg_template": "Template",
        "msg_no_fields": "No fields detected (needs A=Label B=Value layout or {{PLACEHOLDER}} tokens).",
        "err_template": "Template error",
        "warn_template_first": "Load a valid template first.",
        "msg_searching": "Searching online CUI={cui} year={tahun} ...",
        "msg_preview_ready": ("Done: {n} preview rows. REVIEW the FINAL column before export. "
                              "Double-click a row to edit. Estimates are tagged ESTIMATE/AI."),
        "msg_online_first_note": "Note: online search ran first, then AI enriches the data.",
        "msg_ai_searching": "AI ({model}) looking up data about: {nama} ...",
        "msg_ai_touched": ("AI touched {n} rows: AI value becomes the main suggestion when empty, "
                           "or the Alternative for comparison. Please review before export!"),
        "msg_final_proposed": "FINAL = suggested value (online/AI) for all rows.",
        "msg_final_alt": "FINAL = second alternative/estimate (where available).",
        "dlg_edit": "Edit",
        "msg_pick_row": "Select one row first.",
        "dlg_final": "Final value",
        "dlg_export": "Export",
        "msg_export_empty": "Nothing to export - press 'Search online' first.",
        "msg_export_unchecked": "All rows unchecked. Tick at least one.",
        "msg_export_done": "Exported OK: {out} ({n} fields written). Template formatting kept.",
        "msg_export_popup": "Done:\n{out}\n\n{n} fields written.",
        "err_search": "Search error",
        "err_ai": "AI error",
        "err_export": "Export error",
        "msg_models_live": "Live models loaded ({n}). Pick one, then “Use selected model”.",
        "msg_models_fallback": "Offline - showing saved list.",
        "msg_model_set": "Model set: {m}",
        "msg_pick_model": "Select a model first.",
        "tpl_line": "Template: {p} | sheets: {s} | fields detected: {n}",
        "msg_busy_template": "Loading template…",
        "msg_busy_search": "Searching online (ANAF/BNR)…",
        "msg_busy_ai": "AI is looking up data…",
        "msg_busy_models": "Loading model list…",
        "msg_busy_export": "Exporting XLSX…",
        "summary_btn": "Summary",
        "sum_title": "Form summary",
        "sum_save": "Save txt",
        "sum_close": "Close",
        "sum_template": "Template",
        "sum_company": "Company/CUI",
        "sum_year": "Year",
        "sum_complete": "Complete",
        "sum_filled": "filled",
        "sum_empty": "empty",
        "sum_excluded": "excluded (☐)",
        "sum_by_source": "By source",
        "sum_by_sheet": "By sheet",
        "sum_missing": "Empty fields — need attention",
        "sum_detail": "All fields (full detail)",
        "sum_none": "(none)",
        "sum_novalue": "(empty)",
        "sum_saved": "Summary saved: {out}",
        "sum_empty_rows": "No rows — run a search first.",
        "estimate_btn": "3b) Auto-estimate rest",
        "msg_busy_estimate": "AI estimating rest…",
        "msg_no_empty": "No empty fields — all filled!",
        "sheet_label": "Sheet:",
        "sheet_all": "All",
        "dossier_btn": "Dossier TXT",
        "dos_title": "Company dossier",
        "dos_need_name": "Enter company name (or CUI) first.",
        "dos_searching": "Checking {nama} across internet sources…",
        "dos_done": "Dossier done: {status} ({n} evidence) → {out}",
        "dos_popup": "{nama}\nStatus: {status}\n\nSaved:\n{out}",
        "msg_busy_dossier": "Checking company…",
        "msg_formula_skipped": " + {n} formula cells protected",
        "stop_btn": "■ Stop",
        "msg_stopped": "Stopped by user — results discarded.",
        "empty_cui": "(empty)",
        "unnamed": "(unspecified)",
        "default_export_name": "BE2026_complete.xlsx",
    },
}

LANGS = {"ms": "Bahasa Melayu", "en": "English"}
